#pragma once

#define DEBOUNCE 5

/* Handedness. */
#define SPLIT_HAND_PIN GP22
#define	SPLIT_HAND_PIN_LOW_IS_LEFT
#define SERIAL_USART_TX_PIN GP1

/* SPI & PMW3360 settings. */
#define RP_SPI_USE_SPI0 TRUE
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP2
#define SPI_MISO_PIN GP0
#define SPI_MOSI_PIN GP3

#define PMW33XX_CPI 1100
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_CS_PIN GP25
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT

/* Reset. (May not be needed) */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U